# Import Libraries

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns 
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.ensemble import RandomForestClassifier , GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier

from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.preprocessing import LabelEncoder , StandardScaler


import warnings
warnings.filterwarnings('ignore')

# Load Data and Get Info

In [2]:
obesity_train=pd.read_csv('/kaggle/input/playground-series-s4e2/train.csv')

In [3]:
obesity_test=pd.read_csv('/kaggle/input/playground-series-s4e2/test.csv')

In [4]:
obesity_train.head()

id  Gender        Age    Height      Weight family_history_with_overweight  \
0   0    Male  24.443011  1.699998   81.669950                            yes   
1   1  Female  18.000000  1.560000   57.000000                            yes   
2   2  Female  18.000000  1.711460   50.165754                            yes   
3   3  Female  20.952737  1.710730  131.274851                            yes   
4   4    Male  31.641081  1.914186   93.798055                            yes   

  FAVC      FCVC       NCP        CAEC SMOKE      CH2O SCC       FAF  \
0  yes  2.000000  2.983297   Sometimes    no  2.763573  no  0.000000   
1  yes  2.000000  3.000000  Frequently    no  2.000000  no  1.000000   
2  yes  1.880534  1.411685   Sometimes    no  1.910378  no  0.866045   
3  yes  3.000000  3.000000   Sometimes    no  1.674061  no  1.467863   
4  yes  2.679664  1.971472   Sometimes    no  1.979848  no  1.967973   

        TUE       CALC                 MTRANS           NObeyesdad  
0  0.976473  Sometimes  Public_Transportation  Overweight_Level_II  
1  1.000000         no             Automobile        Normal_Weight  
2  1.673584         no  Public_Transportation  Insufficient_Weight  
3  0.780199  Sometimes  Public_Transportation     Obesity_Type_III  
4  0.931721  Sometimes  Public_Transportation  Overweight_Level_II

In [5]:
obesity_train.shape

(20758, 18)

In [6]:
obesity_train.tail()

id Gender        Age    Height      Weight  \
20753  20753   Male  25.137087  1.766626  114.187096   
20754  20754   Male  18.000000  1.710000   50.000000   
20755  20755   Male  20.101026  1.819557  105.580491   
20756  20756   Male  33.852953  1.700000   83.520113   
20757  20757   Male  26.680376  1.816547  118.134898   

      family_history_with_overweight FAVC      FCVC       NCP        CAEC  \
20753                            yes  yes  2.919584  3.000000   Sometimes   
20754                             no  yes  3.000000  4.000000  Frequently   
20755                            yes  yes  2.407817  3.000000   Sometimes   
20756                            yes  yes  2.671238  1.971472   Sometimes   
20757                            yes  yes  3.000000  3.000000   Sometimes   

      SMOKE      CH2O SCC       FAF       TUE       CALC  \
20753    no  2.151809  no  1.330519  0.196680  Sometimes   
20754    no  1.000000  no  2.000000  1.000000  Sometimes   
20755    no  2.000000  no  1.158040  1.198439         no   
20756    no  2.144838  no  0.000000  0.973834         no   
20757    no  2.003563  no  0.684487  0.713823  Sometimes   

                      MTRANS           NObeyesdad  
20753  Public_Transportation      Obesity_Type_II  
20754  Public_Transportation  Insufficient_Weight  
20755  Public_Transportation      Obesity_Type_II  
20756             Automobile  Overweight_Level_II  
20757  Public_Transportation      Obesity_Type_II

In [7]:
obesity_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20758 entries, 0 to 20757
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   id                              20758 non-null  int64  
 1   Gender                          20758 non-null  object 
 2   Age                             20758 non-null  float64
 3   Height                          20758 non-null  float64
 4   Weight                          20758 non-null  float64
 5   family_history_with_overweight  20758 non-null  object 
 6   FAVC                            20758 non-null  object 
 7   FCVC                            20758 non-null  float64
 8   NCP                             20758 non-null  float64
 9   CAEC                            20758 non-null  object 
 10  SMOKE                           20758 non-null  object 
 11  CH2O                            20758 non-null  float64
 12  SCC                             

In [8]:
obesity_train.describe()

id           Age        Height        Weight          FCVC  \
count  20758.00000  20758.000000  20758.000000  20758.000000  20758.000000   
mean   10378.50000     23.841804      1.700245     87.887768      2.445908   
std     5992.46278      5.688072      0.087312     26.379443      0.533218   
min        0.00000     14.000000      1.450000     39.000000      1.000000   
25%     5189.25000     20.000000      1.631856     66.000000      2.000000   
50%    10378.50000     22.815416      1.700000     84.064875      2.393837   
75%    15567.75000     26.000000      1.762887    111.600553      3.000000   
max    20757.00000     61.000000      1.975663    165.057269      3.000000   

                NCP          CH2O           FAF           TUE  
count  20758.000000  20758.000000  20758.000000  20758.000000  
mean       2.761332      2.029418      0.981747      0.616756  
std        0.705375      0.608467      0.838302      0.602113  
min        1.000000      1.000000      0.000000      0.000000  
25%        3.000000      1.792022      0.008013      0.000000  
50%        3.000000      2.000000      1.000000      0.573887  
75%        3.000000      2.549617      1.587406      1.000000  
max        4.000000      3.000000      3.000000      2.000000

In [9]:
obesity_train.isna().sum()

id                                0
Gender                            0
Age                               0
Height                            0
Weight                            0
family_history_with_overweight    0
FAVC                              0
FCVC                              0
NCP                               0
CAEC                              0
SMOKE                             0
CH2O                              0
SCC                               0
FAF                               0
TUE                               0
CALC                              0
MTRANS                            0
NObeyesdad                        0
dtype: int64

In [10]:
obesity_train.duplicated().sum()

0

In [11]:
obesity_train.sample(5)

id  Gender        Age    Height      Weight  \
6351    6351  Female  21.412434  1.817231  152.217135   
4153    4153  Female  25.988668  1.603404  102.555691   
10285  10285  Female  21.000000  1.610000   66.000000   
9115    9115    Male  17.210933  1.819557   58.325122   
1608    1608  Female  26.000000  1.624950  110.676343   

      family_history_with_overweight FAVC    FCVC  NCP       CAEC SMOKE  \
6351                             yes  yes  3.0000  3.0  Sometimes    no   
4153                             yes  yes  3.0000  3.0  Sometimes    no   
10285                             no  yes  3.0000  3.0  Sometimes    no   
9115                             yes  yes  2.5596  4.0  Sometimes    no   
1608                             yes  yes  3.0000  3.0  Sometimes    no   

           CH2O  SCC       FAF       TUE       CALC                 MTRANS  \
6351   2.305521   no  1.956278  0.923760  Sometimes  Public_Transportation   
4153   1.031354   no  0.026033  0.543118  Sometimes  Public_Transportation   
10285  3.000000  yes  0.000000  0.000000  Sometimes  Public_Transportation   
9115   2.000000   no  2.000000  0.000000  Sometimes             Automobile   
1608   2.554007   no  0.000000  0.503896  Sometimes  Public_Transportation   

                NObeyesdad  
6351      Obesity_Type_III  
4153      Obesity_Type_III  
10285   Overweight_Level_I  
9115   Insufficient_Weight  
1608      Obesity_Type_III

In [12]:
obesity_train.columns

Index(['id', 'Gender', 'Age', 'Height', 'Weight',
       'family_history_with_overweight', 'FAVC', 'FCVC', 'NCP', 'CAEC',
       'SMOKE', 'CH2O', 'SCC', 'FAF', 'TUE', 'CALC', 'MTRANS', 'NObeyesdad'],
      dtype='object')

# Preprocessing

Transform object to int

### Train Data

In [13]:
la=LabelEncoder()

In [14]:
ob=obesity_train.select_dtypes(include='object')
non_ob=obesity_train.select_dtypes(exclude='object')

In [15]:
ob.head()

Gender family_history_with_overweight FAVC        CAEC SMOKE SCC  \
0    Male                            yes  yes   Sometimes    no  no   
1  Female                            yes  yes  Frequently    no  no   
2  Female                            yes  yes   Sometimes    no  no   
3  Female                            yes  yes   Sometimes    no  no   
4    Male                            yes  yes   Sometimes    no  no   

        CALC                 MTRANS           NObeyesdad  
0  Sometimes  Public_Transportation  Overweight_Level_II  
1         no             Automobile        Normal_Weight  
2         no  Public_Transportation  Insufficient_Weight  
3  Sometimes  Public_Transportation     Obesity_Type_III  
4  Sometimes  Public_Transportation  Overweight_Level_II

In [16]:
non_ob.head()

id        Age    Height      Weight      FCVC       NCP      CH2O  \
0   0  24.443011  1.699998   81.669950  2.000000  2.983297  2.763573   
1   1  18.000000  1.560000   57.000000  2.000000  3.000000  2.000000   
2   2  18.000000  1.711460   50.165754  1.880534  1.411685  1.910378   
3   3  20.952737  1.710730  131.274851  3.000000  3.000000  1.674061   
4   4  31.641081  1.914186   93.798055  2.679664  1.971472  1.979848   

        FAF       TUE  
0  0.000000  0.976473  
1  1.000000  1.000000  
2  0.866045  1.673584  
3  1.467863  0.780199  
4  1.967973  0.931721

In [17]:
for i in range(0,ob.shape[1]):
    ob.iloc[:,i]=la.fit_transform(ob.iloc[:,i])

In [18]:
ob.head()

Gender family_history_with_overweight FAVC CAEC SMOKE SCC CALC MTRANS  \
0      1                              1    1    2     0   0    1      3   
1      0                              1    1    1     0   0    2      0   
2      0                              1    1    2     0   0    2      3   
3      0                              1    1    2     0   0    1      3   
4      1                              1    1    2     0   0    1      3   

  NObeyesdad  
0          6  
1          1  
2          0  
3          4  
4          6

In [19]:
ob=ob.astype('int')

In [20]:
ob.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20758 entries, 0 to 20757
Data columns (total 9 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Gender                          20758 non-null  int64
 1   family_history_with_overweight  20758 non-null  int64
 2   FAVC                            20758 non-null  int64
 3   CAEC                            20758 non-null  int64
 4   SMOKE                           20758 non-null  int64
 5   SCC                             20758 non-null  int64
 6   CALC                            20758 non-null  int64
 7   MTRANS                          20758 non-null  int64
 8   NObeyesdad                      20758 non-null  int64
dtypes: int64(9)
memory usage: 1.4 MB


In [21]:
obesity_train=pd.concat([ob,non_ob],axis=1)

In [22]:
obesity_train

Gender  family_history_with_overweight  FAVC  CAEC  SMOKE  SCC  CALC  \
0           1                               1     1     2      0    0     1   
1           0                               1     1     1      0    0     2   
2           0                               1     1     2      0    0     2   
3           0                               1     1     2      0    0     1   
4           1                               1     1     2      0    0     1   
...       ...                             ...   ...   ...    ...  ...   ...   
20753       1                               1     1     2      0    0     1   
20754       1                               0     1     1      0    0     1   
20755       1                               1     1     2      0    0     2   
20756       1                               1     1     2      0    0     2   
20757       1                               1     1     2      0    0     1   

       MTRANS  NObeyesdad     id        Age    Height      Weight      FCVC  \
0           3           6      0  24.443011  1.699998   81.669950  2.000000   
1           0           1      1  18.000000  1.560000   57.000000  2.000000   
2           3           0      2  18.000000  1.711460   50.165754  1.880534   
3           3           4      3  20.952737  1.710730  131.274851  3.000000   
4           3           6      4  31.641081  1.914186   93.798055  2.679664   
...       ...         ...    ...        ...       ...         ...       ...   
20753       3           3  20753  25.137087  1.766626  114.187096  2.919584   
20754       3           0  20754  18.000000  1.710000   50.000000  3.000000   
20755       3           3  20755  20.101026  1.819557  105.580491  2.407817   
20756       0           6  20756  33.852953  1.700000   83.520113  2.671238   
20757       3           3  20757  26.680376  1.816547  118.134898  3.000000   

            NCP      CH2O       FAF       TUE  
0      2.983297  2.763573  0.000000  0.976473  
1      3.000000  2.000000  1.000000  1.000000  
2      1.411685  1.910378  0.866045  1.673584  
3      3.000000  1.674061  1.467863  0.780199  
4      1.971472  1.979848  1.967973  0.931721  
...         ...       ...       ...       ...  
20753  3.000000  2.151809  1.330519  0.196680  
20754  4.000000  1.000000  2.000000  1.000000  
20755  3.000000  2.000000  1.158040  1.198439  
20756  1.971472  2.144838  0.000000  0.973834  
20757  3.000000  2.003563  0.684487  0.713823  

[20758 rows x 18 columns]

### Test Data

In [23]:
obj=obesity_test.select_dtypes(include='object')
non_obj=obesity_test.select_dtypes(exclude='object')

In [24]:
obj.head()

Gender family_history_with_overweight FAVC       CAEC SMOKE SCC       CALC  \
0    Male                            yes  yes  Sometimes    no  no  Sometimes   
1  Female                            yes  yes  Sometimes    no  no  Sometimes   
2  Female                            yes  yes  Sometimes    no  no  Sometimes   
3    Male                            yes  yes  Sometimes    no  no  Sometimes   
4  Female                            yes  yes  Sometimes    no  no  Sometimes   

                  MTRANS  
0  Public_Transportation  
1  Public_Transportation  
2  Public_Transportation  
3  Public_Transportation  
4  Public_Transportation

In [25]:
non_obj.head()

id        Age    Height      Weight      FCVC       NCP      CH2O  \
0  20758  26.899886  1.848294  120.644178  2.938616  3.000000  2.825629   
1  20759  21.000000  1.600000   66.000000  2.000000  1.000000  3.000000   
2  20760  26.000000  1.643355  111.600553  3.000000  3.000000  2.621877   
3  20761  20.979254  1.553127  103.669116  2.000000  2.977909  2.786417   
4  20762  26.000000  1.627396  104.835346  3.000000  3.000000  2.653531   

        FAF       TUE  
0  0.855400  0.000000  
1  1.000000  0.000000  
2  0.000000  0.250502  
3  0.094851  0.000000  
4  0.000000  0.741069

In [26]:
for i in range(0,obj.shape[1]):
    obj.iloc[:,i]=la.fit_transform(obj.iloc[:,i])

In [27]:
obj.head()

Gender family_history_with_overweight FAVC CAEC SMOKE SCC CALC MTRANS
0      1                              1    1    2     0   0    2      3
1      0                              1    1    2     0   0    2      3
2      0                              1    1    2     0   0    2      3
3      1                              1    1    2     0   0    2      3
4      0                              1    1    2     0   0    2      3

In [28]:
obj=obj.astype('int')

In [29]:
obj.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13840 entries, 0 to 13839
Data columns (total 8 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Gender                          13840 non-null  int64
 1   family_history_with_overweight  13840 non-null  int64
 2   FAVC                            13840 non-null  int64
 3   CAEC                            13840 non-null  int64
 4   SMOKE                           13840 non-null  int64
 5   SCC                             13840 non-null  int64
 6   CALC                            13840 non-null  int64
 7   MTRANS                          13840 non-null  int64
dtypes: int64(8)
memory usage: 865.1 KB


In [30]:
obesity_test=pd.concat([obj,non_obj],axis=1)

In [31]:
obesity_test

Gender  family_history_with_overweight  FAVC  CAEC  SMOKE  SCC  CALC  \
0           1                               1     1     2      0    0     2   
1           0                               1     1     2      0    0     2   
2           0                               1     1     2      0    0     2   
3           1                               1     1     2      0    0     2   
4           0                               1     1     2      0    0     2   
...       ...                             ...   ...   ...    ...  ...   ...   
13835       1                               1     0     2      0    0     2   
13836       0                               0     1     2      0    0     2   
13837       0                               0     1     1      0    0     2   
13838       1                               1     1     2      0    0     3   
13839       1                               1     1     2      0    0     2   

       MTRANS     id        Age    Height      Weight      FCVC       NCP  \
0           3  20758  26.899886  1.848294  120.644178  2.938616  3.000000   
1           3  20759  21.000000  1.600000   66.000000  2.000000  1.000000   
2           3  20760  26.000000  1.643355  111.600553  3.000000  3.000000   
3           3  20761  20.979254  1.553127  103.669116  2.000000  2.977909   
4           3  20762  26.000000  1.627396  104.835346  3.000000  3.000000   
...       ...    ...        ...       ...         ...       ...       ...   
13835       3  34593  23.327836  1.721384   78.030383  2.813234  3.000000   
13836       3  34594  29.000000  1.590000   62.000000  3.000000  3.000000   
13837       3  34595  22.935612  1.585547   44.376637  3.000000  2.273740   
13838       3  34596  21.000000  1.620000   53.000000  2.000000  3.000000   
13839       3  34597  26.490926  1.812259  120.980508  2.744994  3.000000   

           CH2O       FAF       TUE  
0      2.825629  0.855400  0.000000  
1      3.000000  1.000000  0.000000  
2      2.621877  0.000000  0.250502  
3      2.786417  0.094851  0.000000  
4      2.653531  0.000000  0.741069  
...         ...       ...       ...  
13835  1.000000  0.807076  0.778632  
13836  2.000000  0.000000  0.000000  
13837  2.000000  1.949840  1.000000  
13838  2.000000  3.000000  2.000000  
13839  2.205977  1.304291  0.630866  

[13840 rows x 17 columns]

scaler for large number

In [32]:
ss=StandardScaler()

In [33]:
obesity_test['Age']=ss.fit_transform(obesity_test[['Age']])
obesity_test['Weight']=ss.fit_transform(obesity_test[['Weight']])

In [34]:
obesity_test

Gender  family_history_with_overweight  FAVC  CAEC  SMOKE  SCC  CALC  \
0           1                               1     1     2      0    0     2   
1           0                               1     1     2      0    0     2   
2           0                               1     1     2      0    0     2   
3           1                               1     1     2      0    0     2   
4           0                               1     1     2      0    0     2   
...       ...                             ...   ...   ...    ...  ...   ...   
13835       1                               1     0     2      0    0     2   
13836       0                               0     1     2      0    0     2   
13837       0                               0     1     1      0    0     2   
13838       1                               1     1     2      0    0     3   
13839       1                               1     1     2      0    0     2   

       MTRANS     id       Age    Height    Weight      FCVC       NCP  \
0           3  20758  0.508163  1.848294  1.273786  2.938616  3.000000   
1           3  20759 -0.509128  1.600000 -0.818988  2.000000  1.000000   
2           3  20760  0.353000  1.643355  0.927432  3.000000  3.000000   
3           3  20761 -0.512705  1.553127  0.623672  2.000000  2.977909   
4           3  20762  0.353000  1.627396  0.668336  3.000000  3.000000   
...       ...    ...       ...       ...       ...       ...       ...   
13835       3  34593 -0.107749  1.721384 -0.358246  2.813234  3.000000   
13836       3  34594  0.870277  1.590000 -0.972181  3.000000  3.000000   
13837       3  34595 -0.175379  1.585547 -1.647125  3.000000  2.273740   
13838       3  34596 -0.509128  1.620000 -1.316865  2.000000  3.000000   
13839       3  34597  0.437648  1.812259  1.286667  2.744994  3.000000   

           CH2O       FAF       TUE  
0      2.825629  0.855400  0.000000  
1      3.000000  1.000000  0.000000  
2      2.621877  0.000000  0.250502  
3      2.786417  0.094851  0.000000  
4      2.653531  0.000000  0.741069  
...         ...       ...       ...  
13835  1.000000  0.807076  0.778632  
13836  2.000000  0.000000  0.000000  
13837  2.000000  1.949840  1.000000  
13838  2.000000  3.000000  2.000000  
13839  2.205977  1.304291  0.630866  

[13840 rows x 17 columns]

In [35]:
obesity_train['Age']=ss.fit_transform(obesity_train[['Age']])
obesity_train['Weight']=ss.fit_transform(obesity_train[['Weight']])

In [36]:
obesity_train

Gender  family_history_with_overweight  FAVC  CAEC  SMOKE  SCC  CALC  \
0           1                               1     1     2      0    0     1   
1           0                               1     1     1      0    0     2   
2           0                               1     1     2      0    0     2   
3           0                               1     1     2      0    0     1   
4           1                               1     1     2      0    0     1   
...       ...                             ...   ...   ...    ...  ...   ...   
20753       1                               1     1     2      0    0     1   
20754       1                               0     1     1      0    0     1   
20755       1                               1     1     2      0    0     2   
20756       1                               1     1     2      0    0     2   
20757       1                               1     1     2      0    0     1   

       MTRANS  NObeyesdad     id       Age    Height    Weight      FCVC  \
0           3           6      0  0.105699  1.699998 -0.235713  2.000000   
1           0           1      1 -1.027052  1.560000 -1.170931  2.000000   
2           3           0      2 -1.027052  1.711460 -1.430012  1.880534   
3           3           4      3 -0.507929  1.710730  1.644770  3.000000   
4           3           6      4  1.371197  1.914186  0.224054  2.679664   
...       ...         ...    ...       ...       ...       ...       ...   
20753       3           3  20753  0.227725  1.766626  0.996987  2.919584   
20754       3           0  20754 -1.027052  1.710000 -1.436296  3.000000   
20755       3           3  20755 -0.657669  1.819557  0.670717  2.407817   
20756       0           6  20756  1.760067  1.700000 -0.165574  2.671238   
20757       3           3  20757  0.499051  1.816547  1.146645  3.000000   

            NCP      CH2O       FAF       TUE  
0      2.983297  2.763573  0.000000  0.976473  
1      3.000000  2.000000  1.000000  1.000000  
2      1.411685  1.910378  0.866045  1.673584  
3      3.000000  1.674061  1.467863  0.780199  
4      1.971472  1.979848  1.967973  0.931721  
...         ...       ...       ...       ...  
20753  3.000000  2.151809  1.330519  0.196680  
20754  4.000000  1.000000  2.000000  1.000000  
20755  3.000000  2.000000  1.158040  1.198439  
20756  1.971472  2.144838  0.000000  0.973834  
20757  3.000000  2.003563  0.684487  0.713823  

[20758 rows x 18 columns]

# Build Model

In [37]:
x=obesity_train.drop(['NObeyesdad','id'],axis=1)
y=obesity_train['NObeyesdad']

In [38]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

#### Logistic Regression

In [39]:
Model_LR=LogisticRegression()

In [40]:
Model_LR.fit(x_train,y_train)

LogisticRegression()

In [41]:
Model_LR.predict(x_test)

array([4, 5, 2, ..., 2, 6, 5])

In [42]:
print(classification_report(Model_LR.predict(x_test),y_test))

              precision    recall  f1-score   support

           0       0.85      0.79      0.82       569
           1       0.69      0.70      0.69       615
           2       0.80      0.77      0.78       565
           3       0.97      0.95      0.96       668
           4       1.00      0.99      1.00       807
           5       0.59      0.64      0.62       448
           6       0.60      0.65      0.62       480

    accuracy                           0.81      4152
   macro avg       0.79      0.78      0.78      4152
weighted avg       0.81      0.81      0.81      4152



#### RandomForestClassifier

In [43]:
Model_RF=RandomForestClassifier()

In [44]:
Model_RF.fit(x_train,y_train)

RandomForestClassifier()

In [45]:
Model_RF.predict(x_test)

array([4, 5, 2, ..., 2, 6, 6])

In [46]:
print(classification_report(Model_RF.predict(x_test),y_test))

              precision    recall  f1-score   support

           0       0.92      0.94      0.93       511
           1       0.88      0.84      0.86       659
           2       0.86      0.88      0.87       534
           3       0.97      0.97      0.97       658
           4       1.00      1.00      1.00       805
           5       0.75      0.77      0.76       471
           6       0.79      0.79      0.79       514

    accuracy                           0.89      4152
   macro avg       0.88      0.88      0.88      4152
weighted avg       0.89      0.89      0.89      4152



#### GaussianNB

In [47]:
Model_GNB=GaussianNB()

In [48]:
Model_GNB.fit(x_train,y_train)

GaussianNB()

In [49]:
Model_GNB.predict(x_test)

array([4, 5, 2, ..., 2, 2, 2])

In [50]:
print(classification_report(Model_GNB.predict(x_test),y_test))

              precision    recall  f1-score   support

           0       0.85      0.70      0.77       641
           1       0.47      0.65      0.54       450
           2       0.61      0.37      0.46       897
           3       0.93      0.71      0.81       858
           4       1.00      0.96      0.98       832
           5       0.30      0.61      0.40       239
           6       0.24      0.53      0.33       235

    accuracy                           0.66      4152
   macro avg       0.63      0.65      0.61      4152
weighted avg       0.74      0.66      0.68      4152



#### SVC

In [51]:
Model_SVC=SVC()

In [52]:
Model_SVC.fit(x_train,y_train)

SVC()

In [53]:
Model_SVC.predict(x_test)

array([4, 5, 2, ..., 2, 6, 5])

In [54]:
print(classification_report(Model_SVC.predict(x_test),y_test))

              precision    recall  f1-score   support

           0       0.94      0.87      0.90       564
           1       0.77      0.81      0.79       593
           2       0.84      0.82      0.83       557
           3       0.97      0.97      0.97       659
           4       1.00      1.00      1.00       804
           5       0.66      0.69      0.67       463
           6       0.69      0.70      0.69       512

    accuracy                           0.85      4152
   macro avg       0.84      0.83      0.84      4152
weighted avg       0.85      0.85      0.85      4152



#### XGBClassifier

In [55]:
Model_XGB=XGBClassifier()

In [56]:
Model_XGB.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, objective='multi:softprob', ...)

In [57]:
Model_XGB.predict(x_test)

array([4, 5, 2, ..., 2, 5, 6])

In [58]:
print(classification_report(Model_XGB.predict(x_test),y_test))

              precision    recall  f1-score   support

           0       0.92      0.95      0.93       506
           1       0.89      0.87      0.88       639
           2       0.86      0.89      0.87       527
           3       0.97      0.97      0.97       656
           4       1.00      0.99      1.00       807
           5       0.79      0.77      0.78       494
           6       0.81      0.79      0.80       523

    accuracy                           0.90      4152
   macro avg       0.89      0.89      0.89      4152
weighted avg       0.90      0.90      0.90      4152



#### GradientBoostingClassifier

In [59]:
Model_GBoosting=GradientBoostingClassifier()

In [60]:
Model_GBoosting.fit(x_train,y_train)

GradientBoostingClassifier()

In [61]:
Model_GBoosting.predict(x_test)

array([4, 5, 2, ..., 2, 5, 6])

In [62]:
print(classification_report(Model_GBoosting.predict(x_test),y_test))

              precision    recall  f1-score   support

           0       0.94      0.95      0.94       520
           1       0.88      0.88      0.88       633
           2       0.87      0.88      0.88       537
           3       0.97      0.97      0.97       655
           4       1.00      1.00      1.00       805
           5       0.78      0.78      0.78       486
           6       0.80      0.80      0.80       516

    accuracy                           0.90      4152
   macro avg       0.89      0.89      0.89      4152
weighted avg       0.90      0.90      0.90      4152



# Optimaization

In [63]:
prim_grid={'n_estimators':[100,200,300],
           'learning_rate':[0.1,0.01,0.001],
           'max_depth':[3,5,7]}
scorer="accuracy"

#### XGBClassifier

In [64]:
Model_XGB=GridSearchCV(Model_XGB,prim_grid,scoring=scorer,n_jobs=-1)
Model_XGB.fit(x_train,y_train)
print(Model_XGB.best_params_)
print(Model_XGB.best_score_)

{'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200}
0.9082865301192982


In [65]:
Model_XGB=XGBClassifier({'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200})

In [66]:
Model_XGB.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, objective='multi:softprob', ...)

In [67]:
Model_XGB.predict(x_test)

array([4, 5, 2, ..., 2, 5, 6])

In [68]:
print(classification_report(Model_XGB.predict(x_test),y_test))

              precision    recall  f1-score   support

           0       0.92      0.95      0.93       506
           1       0.89      0.87      0.88       639
           2       0.86      0.89      0.87       527
           3       0.97      0.97      0.97       656
           4       1.00      0.99      1.00       807
           5       0.79      0.77      0.78       494
           6       0.81      0.79      0.80       523

    accuracy                           0.90      4152
   macro avg       0.89      0.89      0.89      4152
weighted avg       0.90      0.90      0.90      4152



# Testing

In [69]:
test_x=obesity_test.drop(['id'],axis=1)

In [70]:
pred=Model_XGB.predict(test_x)

In [71]:
df=pd.DataFrame({'id':obesity_test['id'],'NObeyesdad':pred})

In [72]:
df

id  NObeyesdad
0      20758           3
1      20759           5
2      20760           4
3      20761           2
4      20762           4
...      ...         ...
13835  34593           6
13836  34594           1
13837  34595           0
13838  34596           1
13839  34597           3

[13840 rows x 2 columns]

In [73]:
df.to_csv("sub.csv",index=False)